-- The grammar curriculum, reviewed.
--
-- Three problems with the map as first seeded, all of which a learner walking it would hit:
--
--   * Core topics were missing. There was no "to be" — the first thing anyone learns — and no
--     there is/are, have got, imperatives, used to, past simple vs present perfect, wish,
--     modals of deduction, and almost nothing at C1/C2 (participle clauses, cleft sentences,
--     ellipsis, nominalisation, the subjunctive). 36 topics are added, as drafts: a topic
--     goes live when its content is published, never before.
--   * Topics were listed twice. Comparative and superlative under Adjectives and Comparisons,
--     adjective order and adverb position under Word Order as well, a whole Relative Clauses
--     and Conditionals topic again under Clauses, "state/action verbs" beside "stative
--     verbs", "unless" in two categories, a few / a little apart from few / little. 13 are
--     archived (never deleted: progress on them stays readable). One that is already live is
--     left alone — taking published teaching away belongs to an editor, not a migration.
--   * The order was not a learning order. Within a category, B1 topics came before A2 ones
--     (Present Perfect before Past Simple, May/Might before Must), and the categories began
--     with articles rather than the verbs a beginner meets first. Categories now run from
--     what a beginner needs to what an advanced learner refines, and topics within each run
--     by level.
--
-- curriculum.json in cmd/seed is the same curriculum for a fresh database. Names and
-- descriptions an owner may have edited are only written for the topics added or renamed
-- here; for the rest only placement changes. On an empty database every statement is a
-- no-op: the seed writes the curriculum there.

UPDATE grammar_categories c SET sort_order = v.ord
FROM (VALUES
    ('verbs', 1),
    ('pronouns', 2),
    ('articles', 3),
    ('nouns', 4),
    ('determiners', 5),
    ('tenses', 6),
    ('questions-negation', 7),
    ('prepositions', 8),
    ('adjectives', 9),
    ('adverbs', 10),
    ('comparisons', 11),
    ('modals', 12),
    ('conjunctions', 13),
    ('word-order', 14),
    ('sentence-structure', 15),
    ('gerunds-infinitives', 16),
    ('conditionals', 17),
    ('passive', 18),
    ('reported-speech', 19),
    ('relative-clauses', 20),
    ('clauses', 21)
) AS v(slug, ord)
WHERE c.slug = v.slug;

-- New and renamed topics, in full.
INSERT INTO grammar_topics (slug, name, description, level_id, sort_order, status, category_id,
                            group_label, group_order, cefr_levels, difficulty, keywords,
                            ielts_relevant, estimated_minutes)
SELECT r.slug, r.name, r.description, l.id, r.sort_order, 'draft', c.id,
       r.group_label, r.group_order, r.cefr_levels, r.difficulty, r.keywords,
       r.ielts_relevant, r.estimated_minutes
FROM jsonb_to_recordset($json$[
{"slug": "to-be", "name": "To Be (am / is / are)", "description": "The first verb of English: who and what things are, and how to ask and say no.", "level": "A1", "cefr_levels": ["A1"], "difficulty": 0.05, "estimated_minutes": 10, "ielts_relevant": false, "keywords": ["to be", "am is are", "was were", "i am", "be verb"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 1},
{"slug": "imperatives", "name": "Imperatives", "description": "Telling someone to do something — and not to — with the bare verb, plus let's for suggestions.", "level": "A1", "cefr_levels": ["A1", "A2"], "difficulty": 0.1, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["imperative", "commands", "instructions", "don't", "let's"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 2},
{"slug": "there-is-there-are", "name": "There is / There are", "description": "Saying that something exists or is in a place.", "level": "A1", "cefr_levels": ["A1", "A2"], "difficulty": 0.15, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["there is", "there are", "is there", "there was", "existence"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 3},
{"slug": "have-got", "name": "Have / Have got", "description": "Possession, family and illness with have and have got, and how their questions differ.", "level": "A1", "cefr_levels": ["A1", "A2"], "difficulty": 0.15, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["have got", "has got", "possession", "have"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 4},
{"slug": "like-want-would-like", "name": "Like / Want / Would like", "description": "Saying what you like, want and would like — and why would like is the polite one.", "level": "A1", "cefr_levels": ["A1", "A2"], "difficulty": 0.2, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["would like", "i'd like", "want", "like doing", "polite requests"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 5},
{"slug": "used-to", "name": "Used to", "description": "Past habits and states that are no longer true.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.4, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["used to", "didn't use to", "past habits", "would for habits"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 7},
{"slug": "stative-verbs", "name": "Stative vs Action Verbs", "description": "Verbs for states (know, like, own) that resist the continuous, against verbs for actions.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.6, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["stative verbs", "know like want", "not continuous", "i'm loving it"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 8},
{"slug": "be-get-used-to", "name": "Be used to / Get used to", "description": "Being or becoming accustomed to something — not the same as used to.", "level": "B2", "cefr_levels": ["B2"], "difficulty": 0.65, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["be used to", "get used to", "accustomed", "used to doing"], "category": "verbs", "group_label": "", "group_order": 1, "sort_order": 11},
{"slug": "one-ones", "name": "One / Ones", "description": "Replacing a noun you have just said: the blue one, the old ones.", "level": "B1", "cefr_levels": ["B1"], "difficulty": 0.45, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["one", "ones", "the red one", "substitution"], "category": "pronouns", "group_label": "", "group_order": 1, "sort_order": 7},
{"slug": "singular-plural", "name": "Singular & Plural Nouns", "description": "One thing or more: -s, -es, -ies, and the spelling rules behind them.", "level": "A1", "cefr_levels": ["A1"], "difficulty": 0.15, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["plural", "singular", "-s", "one or many"], "category": "nouns", "group_label": "", "group_order": 1, "sort_order": 1},
{"slug": "partitives", "name": "Partitives (a piece of, a cup of)", "description": "Counting uncountable things with a piece of, a glass of, a loaf of.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.35, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["a piece of", "a cup of", "a bottle of", "uncountable", "quantities"], "category": "nouns", "group_label": "", "group_order": 1, "sort_order": 5},
{"slug": "enough", "name": "Too / Enough", "description": "More than needed, or as much as needed — and where each goes in the sentence.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.4, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["enough", "not enough", "too"], "category": "determiners", "group_label": "", "group_order": 1, "sort_order": 4},
{"slug": "few-little", "name": "Few / A Few / Little / A Little", "description": "Small amounts, and how a changes the meaning from not enough to some.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.45, "estimated_minutes": 8, "ielts_relevant": true, "keywords": ["few", "little", "few or little", "not enough"], "category": "determiners", "group_label": "", "group_order": 1, "sort_order": 5},
{"slug": "other-another", "name": "Another / Other / Others", "description": "One more, the remaining one, and the rest.", "level": "B1", "cefr_levels": ["A2", "B1"], "difficulty": 0.45, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["another", "other", "others", "the other", "each other"], "category": "determiners", "group_label": "", "group_order": 1, "sort_order": 6},
{"slug": "no-none", "name": "No / None", "description": "No before a noun, none on its own or with of.", "level": "B1", "cefr_levels": ["B1"], "difficulty": 0.5, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["no", "none", "none of", "not any"], "category": "determiners", "group_label": "", "group_order": 1, "sort_order": 9},
{"slug": "present-simple-vs-continuous", "name": "Present Simple vs Present Continuous", "description": "Habits and facts against what is happening now.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.35, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["present simple vs continuous", "habits vs now", "always vs now"], "category": "tenses", "group_label": "Present", "group_order": 1, "sort_order": 3},
{"slug": "past-simple-vs-present-perfect", "name": "Past Simple vs Present Perfect", "description": "Finished time against time connected to now — the contrast learners get wrong most.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.6, "estimated_minutes": 15, "ielts_relevant": true, "keywords": ["past simple vs present perfect", "yesterday vs ever", "finished time"], "category": "tenses", "group_label": "Present", "group_order": 1, "sort_order": 5},
{"slug": "narrative-tenses", "name": "Narrative Tenses", "description": "Past simple, past continuous and past perfect working together to tell a story.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.6, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["narrative tenses", "telling stories", "past simple continuous perfect"], "category": "tenses", "group_label": "Past", "group_order": 2, "sort_order": 10},
{"slug": "future-forms-compared", "name": "Will vs Going to vs Present Continuous", "description": "Choosing between the three everyday ways to talk about the future.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.55, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["will vs going to", "future forms", "plans predictions arrangements"], "category": "tenses", "group_label": "Future", "group_order": 3, "sort_order": 15},
{"slug": "future-in-the-past", "name": "Future in the Past", "description": "Talking about the future from a point in the past: I was going to call you.", "level": "C1", "cefr_levels": ["C1"], "difficulty": 0.85, "estimated_minutes": 8, "ielts_relevant": true, "keywords": ["was going to", "would", "future in the past", "was about to"], "category": "tenses", "group_label": "Future", "group_order": 3, "sort_order": 19},
{"slug": "short-answers", "name": "Short Answers", "description": "Answering yes/no questions with the auxiliary: Yes, I do. No, she isn't.", "level": "A1", "cefr_levels": ["A1"], "difficulty": 0.15, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["short answers", "yes i do", "no she isn't", "auxiliary"], "category": "questions-negation", "group_label": "", "group_order": 1, "sort_order": 2},
{"slug": "subject-object-questions", "name": "Subject and Object Questions", "description": "Who called you? against Who did you call? — when the question needs no do.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.45, "estimated_minutes": 10, "ielts_relevant": false, "keywords": ["subject questions", "object questions", "who saw", "who did you see"], "category": "questions-negation", "group_label": "", "group_order": 1, "sort_order": 5},
{"slug": "so-neither", "name": "So do I / Neither do I", "description": "Agreeing with positive and negative statements.", "level": "B1", "cefr_levels": ["B1"], "difficulty": 0.5, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["so do i", "neither do i", "me too", "agreeing"], "category": "questions-negation", "group_label": "", "group_order": 1, "sort_order": 7},
{"slug": "adjectives-basics", "name": "Adjectives: Position and Use", "description": "Where adjectives go and why they never take -s.", "level": "A1", "cefr_levels": ["A1"], "difficulty": 0.1, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["adjective", "before nouns", "after be", "describing"], "category": "adjectives", "group_label": "", "group_order": 1, "sort_order": 1},
{"slug": "still-yet-already", "name": "Still / Yet / Already", "description": "Something continuing, expected, or sooner than expected.", "level": "B1", "cefr_levels": ["A2", "B1"], "difficulty": 0.45, "estimated_minutes": 8, "ielts_relevant": true, "keywords": ["still", "yet", "already", "present perfect"], "category": "adverbs", "group_label": "", "group_order": 1, "sort_order": 5},
{"slug": "so-such", "name": "So / Such", "description": "So with adjectives and adverbs, such with nouns — and the result clauses that follow.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.5, "estimated_minutes": 8, "ielts_relevant": true, "keywords": ["so", "such", "such a", "so that", "so much"], "category": "adverbs", "group_label": "", "group_order": 1, "sort_order": 7},
{"slug": "shall", "name": "Shall", "description": "", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.35, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["shall", "offers", "suggestions", "formal future"], "category": "modals", "group_label": "", "group_order": 1, "sort_order": 5},
{"slug": "be-able-to", "name": "Be able to", "description": "Ability in tenses can does not have, and managing to do something once.", "level": "A2", "cefr_levels": ["A2", "B1"], "difficulty": 0.4, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["be able to", "was able to", "will be able to", "ability"], "category": "modals", "group_label": "", "group_order": 1, "sort_order": 6},
{"slug": "ought-to", "name": "Ought To", "description": "", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.5, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["ought to", "should", "advice"], "category": "modals", "group_label": "", "group_order": 1, "sort_order": 9},
{"slug": "had-better", "name": "Had better", "description": "Strong advice with a warning: you'd better leave now.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.5, "estimated_minutes": 6, "ielts_relevant": false, "keywords": ["had better", "'d better", "strong advice", "warning"], "category": "modals", "group_label": "", "group_order": 1, "sort_order": 10},
{"slug": "modals-of-deduction", "name": "Modals of Deduction (must / might / can't)", "description": "How sure you are about the present: it must be, it might be, it can't be.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.6, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["must be", "can't be", "might be", "deduction", "certainty"], "category": "modals", "group_label": "", "group_order": 1, "sort_order": 11},
{"slug": "would-rather", "name": "Would rather / Would prefer", "description": "Preferences, and what follows each of them.", "level": "B2", "cefr_levels": ["B2"], "difficulty": 0.65, "estimated_minutes": 8, "ielts_relevant": false, "keywords": ["would rather", "would prefer", "prefer to", "rather than"], "category": "modals", "group_label": "", "group_order": 1, "sort_order": 13},
{"slug": "time-clauses", "name": "Time Clauses (when, until, as soon as)", "description": "Clauses of time, and why they take a present tense when they talk about the future.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.5, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["when", "until", "as soon as", "before after", "future time clause"], "category": "conjunctions", "group_label": "", "group_order": 1, "sort_order": 3},
{"slug": "purpose-clauses", "name": "Purpose (to / in order to / so that)", "description": "Saying why someone does something.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.5, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["in order to", "so that", "to + verb", "so as to", "purpose"], "category": "conjunctions", "group_label": "", "group_order": 1, "sort_order": 4},
{"slug": "discourse-markers", "name": "Linking Words (however, therefore, moreover)", "description": "Connecting sentences and paragraphs in formal writing — the cohesion IELTS marks.", "level": "B2", "cefr_levels": ["B2", "C1"], "difficulty": 0.65, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["however", "therefore", "moreover", "furthermore", "linking words", "discourse markers"], "category": "conjunctions", "group_label": "", "group_order": 1, "sort_order": 10},
{"slug": "ellipsis-substitution", "name": "Ellipsis & Substitution", "description": "Leaving out or replacing words a listener can recover: I hope so, She might.", "level": "C1", "cefr_levels": ["C1", "C2"], "difficulty": 0.85, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["ellipsis", "substitution", "so do i", "i think so", "leaving words out"], "category": "sentence-structure", "group_label": "", "group_order": 1, "sort_order": 9},
{"slug": "nominalisation", "name": "Nominalisation", "description": "Turning verbs and adjectives into nouns for a formal, academic style.", "level": "C1", "cefr_levels": ["C1", "C2"], "difficulty": 0.85, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["nominalisation", "nominalization", "noun phrases", "academic style"], "category": "sentence-structure", "group_label": "", "group_order": 1, "sort_order": 10},
{"slug": "unless-cond", "name": "Unless", "description": "Unless meaning if not, and where it cannot replace it.", "level": "B1", "cefr_levels": ["B1", "B2"], "difficulty": 0.65, "estimated_minutes": 8, "ielts_relevant": true, "keywords": ["unless", "if not", "negative condition"], "category": "conditionals", "group_label": "", "group_order": 1, "sort_order": 3},
{"slug": "wish-if-only", "name": "Wish / If only", "description": "Wishes and regrets about the present, the past and other people's behaviour.", "level": "B2", "cefr_levels": ["B2", "C1"], "difficulty": 0.75, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["wish", "if only", "regret", "i wish i had", "wish would"], "category": "conditionals", "group_label": "", "group_order": 1, "sort_order": 7},
{"slug": "passive-reporting", "name": "Passive Reporting (it is said that)", "description": "Reporting what people say or believe without saying who: He is thought to be abroad.", "level": "C1", "cefr_levels": ["C1", "C2"], "difficulty": 0.85, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["it is said that", "is believed to", "passive reporting", "impersonal passive"], "category": "passive", "group_label": "", "group_order": 1, "sort_order": 7},
{"slug": "participle-clauses", "name": "Participle Clauses", "description": "Shortening clauses with -ing, -ed and having done: Walking home, I saw her.", "level": "C1", "cefr_levels": ["C1", "C2"], "difficulty": 0.85, "estimated_minutes": 12, "ielts_relevant": true, "keywords": ["participle clause", "having done", "-ing clause", "-ed clause"], "category": "clauses", "group_label": "", "group_order": 1, "sort_order": 3},
{"slug": "cleft-sentences", "name": "Cleft Sentences", "description": "Emphasis by splitting a sentence: It was Tom who called. What I need is sleep.", "level": "C1", "cefr_levels": ["C1", "C2"], "difficulty": 0.85, "estimated_minutes": 10, "ielts_relevant": true, "keywords": ["cleft sentence", "it was that", "what i need is", "emphasis"], "category": "clauses", "group_label": "", "group_order": 1, "sort_order": 4},
{"slug": "subjunctive", "name": "The Subjunctive", "description": "Formal mandative structures: It is vital that she be informed.", "level": "C1", "cefr_levels": ["C1", "C2"], "difficulty": 0.9, "estimated_minutes": 8, "ielts_relevant": true, "keywords": ["subjunctive", "i suggest he go", "it is essential that", "if i were"], "category": "clauses", "group_label": "", "group_order": 1, "sort_order": 5}
]$json$::jsonb) AS r(slug text, name text, description text, level text, cefr_levels text[],
                     difficulty numeric, estimated_minutes int, ielts_relevant boolean,
                     keywords text[], category text, group_label text, group_order int, sort_order int)
JOIN grammar_categories c ON c.slug = r.category
LEFT JOIN levels l ON l.code = r.level
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name, description = EXCLUDED.description, level_id = EXCLUDED.level_id,
    cefr_levels = EXCLUDED.cefr_levels, difficulty = EXCLUDED.difficulty,
    -- A topic coming back into the curriculum is a draft again until content is published.
    status = CASE WHEN grammar_topics.status = 'archived' THEN 'draft' ELSE grammar_topics.status END;

-- Where every topic sits.
UPDATE grammar_topics t SET
    category_id = c.id, group_label = v.grp, group_order = v.grp_order, sort_order = v.ord
FROM (VALUES
    ('to-be', 'verbs', '', 1, 1),
    ('imperatives', 'verbs', '', 1, 2),
    ('there-is-there-are', 'verbs', '', 1, 3),
    ('have-got', 'verbs', '', 1, 4),
    ('like-want-would-like', 'verbs', '', 1, 5),
    ('regular-irregular-verbs', 'verbs', '', 1, 6),
    ('used-to', 'verbs', '', 1, 7),
    ('stative-verbs', 'verbs', '', 1, 8),
    ('phrasal-verbs', 'verbs', '', 1, 9),
    ('transitive-intransitive', 'verbs', '', 1, 10),
    ('be-get-used-to', 'verbs', '', 1, 11),
    ('causative-verbs', 'verbs', '', 1, 12),
    ('subject-pronouns', 'pronouns', '', 1, 1),
    ('object-pronouns', 'pronouns', '', 1, 2),
    ('possessive-adjectives', 'pronouns', '', 1, 3),
    ('possessive-pronouns', 'pronouns', '', 1, 4),
    ('reflexive-pronouns', 'pronouns', '', 1, 5),
    ('indefinite-pronouns', 'pronouns', '', 1, 6),
    ('one-ones', 'pronouns', '', 1, 7),
    ('a-an', 'articles', '', 1, 1),
    ('the', 'articles', '', 1, 2),
    ('zero-article', 'articles', '', 1, 3),
    ('a-an-vs-the', 'articles', '', 1, 4),
    ('articles-institutions', 'articles', '', 1, 5),
    ('articles-geographical', 'articles', '', 1, 6),
    ('articles-proper', 'articles', '', 1, 7),
    ('articles-abstract', 'articles', '', 1, 8),
    ('singular-plural', 'nouns', '', 1, 1),
    ('irregular-plurals', 'nouns', '', 1, 2),
    ('countable-uncountable', 'nouns', '', 1, 3),
    ('possessive-nouns', 'nouns', '', 1, 4),
    ('partitives', 'nouns', '', 1, 5),
    ('compound-nouns', 'nouns', '', 1, 6),
    ('collective-nouns', 'nouns', '', 1, 7),
    ('this-that-these-those', 'determiners', '', 1, 1),
    ('some-any', 'determiners', '', 1, 2),
    ('much-many', 'determiners', '', 1, 3),
    ('enough', 'determiners', '', 1, 4),
    ('few-little', 'determiners', '', 1, 5),
    ('other-another', 'determiners', '', 1, 6),
    ('each-every', 'determiners', '', 1, 7),
    ('both-either-neither', 'determiners', '', 1, 8),
    ('no-none', 'determiners', '', 1, 9),
    ('several', 'determiners', '', 1, 10),
    ('all-whole', 'determiners', '', 1, 11),
    ('present-simple', 'tenses', 'Present', 1, 1),
    ('present-continuous', 'tenses', 'Present', 1, 2),
    ('present-simple-vs-continuous', 'tenses', 'Present', 1, 3),
    ('present-perfect', 'tenses', 'Present', 1, 4),
    ('past-simple-vs-present-perfect', 'tenses', 'Present', 1, 5),
    ('present-perfect-continuous', 'tenses', 'Present', 1, 6),
    ('past-simple', 'tenses', 'Past', 2, 7),
    ('past-continuous', 'tenses', 'Past', 2, 8),
    ('past-perfect', 'tenses', 'Past', 2, 9),
    ('narrative-tenses', 'tenses', 'Past', 2, 10),
    ('past-perfect-continuous', 'tenses', 'Past', 2, 11),
    ('be-going-to', 'tenses', 'Future', 3, 12),
    ('future-will', 'tenses', 'Future', 3, 13),
    ('present-continuous-future', 'tenses', 'Future', 3, 14),
    ('future-forms-compared', 'tenses', 'Future', 3, 15),
    ('future-continuous', 'tenses', 'Future', 3, 16),
    ('future-perfect', 'tenses', 'Future', 3, 17),
    ('future-perfect-continuous', 'tenses', 'Future', 3, 18),
    ('future-in-the-past', 'tenses', 'Future', 3, 19),
    ('yes-no-questions', 'questions-negation', '', 1, 1),
    ('short-answers', 'questions-negation', '', 1, 2),
    ('negative-forms', 'questions-negation', '', 1, 3),
    ('wh-questions', 'questions-negation', '', 1, 4),
    ('subject-object-questions', 'questions-negation', '', 1, 5),
    ('question-tags', 'questions-negation', '', 1, 6),
    ('so-neither', 'questions-negation', '', 1, 7),
    ('indirect-questions', 'questions-negation', '', 1, 8),
    ('double-negatives', 'questions-negation', '', 1, 9),
    ('prepositions-time', 'prepositions', '', 1, 1),
    ('prepositions-place', 'prepositions', '', 1, 2),
    ('prepositions-movement', 'prepositions', '', 1, 3),
    ('prepositions-after-adjectives', 'prepositions', '', 1, 4),
    ('prepositions-after-verbs', 'prepositions', '', 1, 5),
    ('prepositional-phrases', 'prepositions', '', 1, 6),
    ('adjectives-basics', 'adjectives', '', 1, 1),
    ('participial-adjectives', 'adjectives', '', 1, 2),
    ('adjective-order', 'adjectives', '', 1, 3),
    ('compound-adjectives', 'adjectives', '', 1, 4),
    ('adverbs-frequency', 'adverbs', '', 1, 1),
    ('adverbs-manner', 'adverbs', '', 1, 2),
    ('adverbs-place', 'adverbs', '', 1, 3),
    ('adverbs-time', 'adverbs', '', 1, 4),
    ('still-yet-already', 'adverbs', '', 1, 5),
    ('adverbs-degree', 'adverbs', '', 1, 6),
    ('so-such', 'adverbs', '', 1, 7),
    ('position-of-adverbs', 'adverbs', '', 1, 8),
    ('sentence-adverbs', 'adverbs', '', 1, 9),
    ('comparative', 'comparisons', '', 1, 1),
    ('superlative', 'comparisons', '', 1, 2),
    ('as-as', 'comparisons', '', 1, 3),
    ('less-fewer', 'comparisons', '', 1, 4),
    ('the-the', 'comparisons', '', 1, 5),
    ('can-could', 'modals', '', 1, 1),
    ('must', 'modals', '', 1, 2),
    ('have-to', 'modals', '', 1, 3),
    ('should', 'modals', '', 1, 4),
    ('shall', 'modals', '', 1, 5),
    ('be-able-to', 'modals', '', 1, 6),
    ('would', 'modals', '', 1, 7),
    ('may-might', 'modals', '', 1, 8),
    ('ought-to', 'modals', '', 1, 9),
    ('had-better', 'modals', '', 1, 10),
    ('modals-of-deduction', 'modals', '', 1, 11),
    ('need-neednt', 'modals', '', 1, 12),
    ('would-rather', 'modals', '', 1, 13),
    ('modal-perfects', 'modals', '', 1, 14),
    ('and-but-or', 'conjunctions', '', 1, 1),
    ('because-so', 'conjunctions', '', 1, 2),
    ('time-clauses', 'conjunctions', '', 1, 3),
    ('purpose-clauses', 'conjunctions', '', 1, 4),
    ('although-though', 'conjunctions', '', 1, 5),
    ('since-conj', 'conjunctions', '', 1, 6),
    ('while-whereas', 'conjunctions', '', 1, 7),
    ('as-conj', 'conjunctions', '', 1, 8),
    ('despite-in-spite-of', 'conjunctions', '', 1, 9),
    ('discourse-markers', 'conjunctions', '', 1, 10),
    ('basic-word-order', 'word-order', '', 1, 1),
    ('question-word-order', 'word-order', '', 1, 2),
    ('inversion', 'word-order', '', 1, 3),
    ('subject', 'sentence-structure', '', 1, 1),
    ('simple-sentences', 'sentence-structure', '', 1, 2),
    ('predicate', 'sentence-structure', '', 1, 3),
    ('objects', 'sentence-structure', '', 1, 4),
    ('compound-sentences', 'sentence-structure', '', 1, 5),
    ('complex-sentences', 'sentence-structure', '', 1, 6),
    ('complements', 'sentence-structure', '', 1, 7),
    ('compound-complex', 'sentence-structure', '', 1, 8),
    ('ellipsis-substitution', 'sentence-structure', '', 1, 9),
    ('nominalisation', 'sentence-structure', '', 1, 10),
    ('gerunds', 'gerunds-infinitives', '', 1, 1),
    ('infinitives', 'gerunds-infinitives', '', 1, 2),
    ('verb-gerund', 'gerunds-infinitives', '', 1, 3),
    ('verb-infinitive', 'gerunds-infinitives', '', 1, 4),
    ('verb-object-infinitive', 'gerunds-infinitives', '', 1, 5),
    ('gerund-vs-infinitive', 'gerunds-infinitives', '', 1, 6),
    ('zero-conditional', 'conditionals', '', 1, 1),
    ('first-conditional', 'conditionals', '', 1, 2),
    ('unless-cond', 'conditionals', '', 1, 3),
    ('second-conditional', 'conditionals', '', 1, 4),
    ('third-conditional', 'conditionals', '', 1, 5),
    ('as-long-as', 'conditionals', '', 1, 6),
    ('wish-if-only', 'conditionals', '', 1, 7),
    ('mixed-conditionals', 'conditionals', '', 1, 8),
    ('provided-providing', 'conditionals', '', 1, 9),
    ('present-passive', 'passive', '', 1, 1),
    ('past-passive', 'passive', '', 1, 2),
    ('future-passive', 'passive', '', 1, 3),
    ('modal-passive', 'passive', '', 1, 4),
    ('perfect-passive', 'passive', '', 1, 5),
    ('get-passive', 'passive', '', 1, 6),
    ('passive-reporting', 'passive', '', 1, 7),
    ('reported-statements', 'reported-speech', '', 1, 1),
    ('reported-questions', 'reported-speech', '', 1, 2),
    ('reported-commands', 'reported-speech', '', 1, 3),
    ('backshift', 'reported-speech', '', 1, 4),
    ('reporting-verbs', 'reported-speech', '', 1, 5),
    ('who-which-that', 'relative-clauses', '', 1, 1),
    ('defining-relative', 'relative-clauses', '', 1, 2),
    ('whose', 'relative-clauses', '', 1, 3),
    ('where-when', 'relative-clauses', '', 1, 4),
    ('non-defining-relative', 'relative-clauses', '', 1, 5),
    ('reduced-relative', 'relative-clauses', '', 1, 6),
    ('noun-clauses', 'clauses', '', 1, 1),
    ('adverbial-clauses', 'clauses', '', 1, 2),
    ('participle-clauses', 'clauses', '', 1, 3),
    ('cleft-sentences', 'clauses', '', 1, 4),
    ('subjunctive', 'clauses', '', 1, 5)
) AS v(slug, category, grp, grp_order, ord)
JOIN grammar_categories c ON c.slug = v.category
WHERE t.slug = v.slug;

-- Duplicates leave the map.
UPDATE grammar_topics SET status = 'archived'
WHERE status <> 'published' AND slug IN ('comparative-adj', 'superlative-adj', 'adjective-order-wo', 'adverb-position', 'relative-clauses-overview', 'conditional-clauses', 'state-action-verbs', 'unless-conj', 'relative-pronouns', 'demonstrative-pronouns', 'more-most', 'regular-plurals', 'a-few-a-little');
