-- Irregular verbs: the table every learner has to know, and practise.
--
-- Unlike the rest of the lexicon these are not generated: there are about a hundred and sixty
-- of them in use, their forms do not change, and a wrong form taught is worse than none. So
-- the list is curated here, once. A form with two accepted spellings keeps both, "learnt /
-- learned", British first. pattern is how the three forms relate — the way the table is
-- learned in groups: AAA cut-cut-cut, ABB buy-bought-bought, ABA come-came-come, ABC
-- go-went-gone. examples ({"base", "past", "participle"}: one sentence each) are written by
-- the AI the first time the list is read, and stored.
CREATE TABLE irregular_verbs (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    base            TEXT        NOT NULL UNIQUE,
    past            TEXT        NOT NULL,
    past_participle TEXT        NOT NULL,
    pattern         TEXT        NOT NULL CHECK (pattern IN ('AAA', 'ABB', 'ABA', 'ABC')),
    level_code      TEXT        NOT NULL CHECK (level_code IN ('A1', 'A2', 'B1', 'B2', 'C1', 'C2')),
    uz              TEXT        NOT NULL DEFAULT '',
    ru              TEXT        NOT NULL DEFAULT '',
    -- What trips learners up about this one verb, in Uzbek: "read" in the past is said /red/.
    note            TEXT        NOT NULL DEFAULT '',
    examples        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX irregular_verbs_level_idx ON irregular_verbs (level_code, pattern);

-- How each learner is doing with each verb: what practice marks and what "my mistakes" lists.
CREATE TABLE user_irregular_verbs (
    user_id        UUID        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    verb_id        UUID        NOT NULL REFERENCES irregular_verbs (id) ON DELETE CASCADE,
    correct        INTEGER     NOT NULL DEFAULT 0,
    wrong          INTEGER     NOT NULL DEFAULT 0,
    -- Right answers in a row since the last mistake: three and the verb counts as known.
    streak         INTEGER     NOT NULL DEFAULT 0,
    last_wrong     JSONB,
    practiced_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, verb_id)
);

INSERT INTO irregular_verbs (base, past, past_participle, pattern, level_code, uz, ru) VALUES
    ('be', 'was / were', 'been', 'ABC', 'A1', 'bo''lmoq', 'быть'),
    ('begin', 'began', 'begun', 'ABC', 'A1', 'boshlamoq', 'начинать'),
    ('buy', 'bought', 'bought', 'ABB', 'A1', 'sotib olmoq', 'покупать'),
    ('come', 'came', 'come', 'ABA', 'A1', 'kelmoq', 'приходить'),
    ('do', 'did', 'done', 'ABC', 'A1', 'qilmoq', 'делать'),
    ('drink', 'drank', 'drunk', 'ABC', 'A1', 'ichmoq', 'пить'),
    ('drive', 'drove', 'driven', 'ABC', 'A1', 'haydamoq (mashina)', 'водить'),
    ('eat', 'ate', 'eaten', 'ABC', 'A1', 'yemoq', 'есть'),
    ('feel', 'felt', 'felt', 'ABB', 'A1', 'his qilmoq', 'чувствовать'),
    ('find', 'found', 'found', 'ABB', 'A1', 'topmoq', 'находить'),
    ('fly', 'flew', 'flown', 'ABC', 'A1', 'uchmoq', 'летать'),
    ('get', 'got', 'got / gotten', 'ABB', 'A1', 'olmoq, ega bo''lmoq', 'получать'),
    ('give', 'gave', 'given', 'ABC', 'A1', 'bermoq', 'давать'),
    ('go', 'went', 'gone', 'ABC', 'A1', 'bormoq', 'идти'),
    ('have', 'had', 'had', 'ABB', 'A1', 'ega bo''lmoq', 'иметь'),
    ('know', 'knew', 'known', 'ABC', 'A1', 'bilmoq', 'знать'),
    ('leave', 'left', 'left', 'ABB', 'A1', 'ketmoq, qoldirmoq', 'уходить, оставлять'),
    ('make', 'made', 'made', 'ABB', 'A1', 'yasamoq, qilmoq', 'делать, создавать'),
    ('meet', 'met', 'met', 'ABB', 'A1', 'uchrashmoq', 'встречать'),
    ('pay', 'paid', 'paid', 'ABB', 'A1', 'to''lamoq', 'платить'),
    ('put', 'put', 'put', 'AAA', 'A1', 'qo''ymoq', 'класть'),
    ('read', 'read', 'read', 'AAA', 'A1', 'o''qimoq', 'читать'),
    ('ride', 'rode', 'ridden', 'ABC', 'A1', 'minmoq (velosiped, ot)', 'ездить верхом'),
    ('run', 'ran', 'run', 'ABA', 'A1', 'yugurmoq', 'бегать'),
    ('say', 'said', 'said', 'ABB', 'A1', 'aytmoq', 'сказать'),
    ('see', 'saw', 'seen', 'ABC', 'A1', 'ko''rmoq', 'видеть'),
    ('sell', 'sold', 'sold', 'ABB', 'A1', 'sotmoq', 'продавать'),
    ('send', 'sent', 'sent', 'ABB', 'A1', 'yubormoq', 'отправлять'),
    ('sing', 'sang', 'sung', 'ABC', 'A1', 'kuylamoq', 'петь'),
    ('sit', 'sat', 'sat', 'ABB', 'A1', 'o''tirmoq', 'сидеть'),
    ('sleep', 'slept', 'slept', 'ABB', 'A1', 'uxlamoq', 'спать'),
    ('speak', 'spoke', 'spoken', 'ABC', 'A1', 'gapirmoq', 'говорить'),
    ('swim', 'swam', 'swum', 'ABC', 'A1', 'suzmoq', 'плавать'),
    ('take', 'took', 'taken', 'ABC', 'A1', 'olmoq', 'брать'),
    ('teach', 'taught', 'taught', 'ABB', 'A1', 'o''rgatmoq', 'учить, преподавать'),
    ('tell', 'told', 'told', 'ABB', 'A1', 'aytib bermoq', 'рассказывать'),
    ('think', 'thought', 'thought', 'ABB', 'A1', 'o''ylamoq', 'думать'),
    ('understand', 'understood', 'understood', 'ABB', 'A1', 'tushunmoq', 'понимать'),
    ('wake', 'woke', 'woken', 'ABC', 'A1', 'uyg''onmoq', 'просыпаться'),
    ('wear', 'wore', 'worn', 'ABC', 'A1', 'kiymoq', 'носить (одежду)'),
    ('win', 'won', 'won', 'ABB', 'A1', 'yutmoq', 'побеждать'),
    ('write', 'wrote', 'written', 'ABC', 'A1', 'yozmoq', 'писать'),
    ('become', 'became', 'become', 'ABA', 'A2', 'bo''lib qolmoq', 'становиться'),
    ('break', 'broke', 'broken', 'ABC', 'A2', 'sindirmoq', 'ломать'),
    ('bring', 'brought', 'brought', 'ABB', 'A2', 'olib kelmoq', 'приносить'),
    ('build', 'built', 'built', 'ABB', 'A2', 'qurmoq', 'строить'),
    ('catch', 'caught', 'caught', 'ABB', 'A2', 'tutmoq, ushlamoq', 'ловить'),
    ('choose', 'chose', 'chosen', 'ABC', 'A2', 'tanlamoq', 'выбирать'),
    ('cost', 'cost', 'cost', 'AAA', 'A2', 'turmoq (narxi)', 'стоить'),
    ('cut', 'cut', 'cut', 'AAA', 'A2', 'kesmoq', 'резать'),
    ('draw', 'drew', 'drawn', 'ABC', 'A2', 'chizmoq', 'рисовать'),
    ('fall', 'fell', 'fallen', 'ABC', 'A2', 'yiqilmoq', 'падать'),
    ('feed', 'fed', 'fed', 'ABB', 'A2', 'ovqatlantirmoq', 'кормить'),
    ('fight', 'fought', 'fought', 'ABB', 'A2', 'urishmoq, kurashmoq', 'драться, бороться'),
    ('forget', 'forgot', 'forgotten', 'ABC', 'A2', 'unutmoq', 'забывать'),
    ('grow', 'grew', 'grown', 'ABC', 'A2', 'o''smoq', 'расти'),
    ('hear', 'heard', 'heard', 'ABB', 'A2', 'eshitmoq', 'слышать'),
    ('hide', 'hid', 'hidden', 'ABC', 'A2', 'yashirmoq', 'прятать'),
    ('hit', 'hit', 'hit', 'AAA', 'A2', 'urmoq', 'ударять'),
    ('hold', 'held', 'held', 'ABB', 'A2', 'ushlab turmoq', 'держать'),
    ('hurt', 'hurt', 'hurt', 'AAA', 'A2', 'og''ritmoq', 'причинять боль'),
    ('keep', 'kept', 'kept', 'ABB', 'A2', 'saqlamoq', 'хранить, держать'),
    ('lend', 'lent', 'lent', 'ABB', 'A2', 'qarzga bermoq', 'одалживать'),
    ('let', 'let', 'let', 'AAA', 'A2', 'ruxsat bermoq', 'позволять'),
    ('lose', 'lost', 'lost', 'ABB', 'A2', 'yo''qotmoq', 'терять'),
    ('mean', 'meant', 'meant', 'ABB', 'A2', 'anglatmoq', 'значить'),
    ('ring', 'rang', 'rung', 'ABC', 'A2', 'jiringlamoq', 'звонить'),
    ('set', 'set', 'set', 'AAA', 'A2', 'o''rnatmoq', 'устанавливать'),
    ('shut', 'shut', 'shut', 'AAA', 'A2', 'yopmoq', 'закрывать'),
    ('spend', 'spent', 'spent', 'ABB', 'A2', 'sarflamoq', 'тратить'),
    ('stand', 'stood', 'stood', 'ABB', 'A2', 'turmoq', 'стоять'),
    ('steal', 'stole', 'stolen', 'ABC', 'A2', 'o''g''irlamoq', 'красть'),
    ('throw', 'threw', 'thrown', 'ABC', 'A2', 'otmoq, tashlamoq', 'бросать'),
    ('learn', 'learnt / learned', 'learnt / learned', 'ABB', 'A2', 'o''rganmoq', 'учить, изучать'),
    ('beat', 'beat', 'beaten', 'ABC', 'B1', 'yengmoq, urmoq', 'бить, побеждать'),
    ('bend', 'bent', 'bent', 'ABB', 'B1', 'egmoq', 'сгибать'),
    ('bet', 'bet', 'bet', 'AAA', 'B1', 'garov o''ynamoq', 'спорить на деньги'),
    ('bite', 'bit', 'bitten', 'ABC', 'B1', 'tishlamoq', 'кусать'),
    ('bleed', 'bled', 'bled', 'ABB', 'B1', 'qon ketmoq', 'кровоточить'),
    ('blow', 'blew', 'blown', 'ABC', 'B1', 'puflamoq, esmoq', 'дуть'),
    ('burn', 'burnt / burned', 'burnt / burned', 'ABB', 'B1', 'yondirmoq', 'жечь'),
    ('dig', 'dug', 'dug', 'ABB', 'B1', 'qazimoq', 'копать'),
    ('dream', 'dreamt / dreamed', 'dreamt / dreamed', 'ABB', 'B1', 'tush ko''rmoq, orzu qilmoq', 'мечтать, видеть сон'),
    ('forgive', 'forgave', 'forgiven', 'ABC', 'B1', 'kechirmoq', 'прощать'),
    ('freeze', 'froze', 'frozen', 'ABC', 'B1', 'muzlamoq', 'замерзать'),
    ('hang', 'hung', 'hung', 'ABB', 'B1', 'osmoq', 'вешать'),
    ('lay', 'laid', 'laid', 'ABB', 'B1', 'yotqizmoq, qo''ymoq', 'класть, положить'),
    ('lead', 'led', 'led', 'ABB', 'B1', 'boshqarmoq, yetaklamoq', 'вести, руководить'),
    ('lie', 'lay', 'lain', 'ABC', 'B1', 'yotmoq', 'лежать'),
    ('light', 'lit', 'lit', 'ABB', 'B1', 'yoqmoq (olov)', 'зажигать'),
    ('mistake', 'mistook', 'mistaken', 'ABC', 'B1', 'adashtirmoq', 'ошибаться, путать'),
    ('overcome', 'overcame', 'overcome', 'ABA', 'B1', 'yengib o''tmoq', 'преодолевать'),
    ('shake', 'shook', 'shaken', 'ABC', 'B1', 'silkitmoq', 'трясти'),
    ('shine', 'shone', 'shone', 'ABB', 'B1', 'porlamoq', 'сиять'),
    ('shoot', 'shot', 'shot', 'ABB', 'B1', 'otmoq (quroldan)', 'стрелять'),
    ('show', 'showed', 'shown', 'ABC', 'B1', 'ko''rsatmoq', 'показывать'),
    ('sink', 'sank', 'sunk', 'ABC', 'B1', 'cho''kmoq', 'тонуть'),
    ('smell', 'smelt / smelled', 'smelt / smelled', 'ABB', 'B1', 'hidlamoq', 'пахнуть, нюхать'),
    ('spell', 'spelt / spelled', 'spelt / spelled', 'ABB', 'B1', 'harflab aytmoq', 'писать по буквам'),
    ('spill', 'spilt / spilled', 'spilt / spilled', 'ABB', 'B1', 'to''kib yubormoq', 'проливать'),
    ('spread', 'spread', 'spread', 'AAA', 'B1', 'yoymoq', 'распространять'),
    ('stick', 'stuck', 'stuck', 'ABB', 'B1', 'yopishtirmoq', 'приклеивать'),
    ('sting', 'stung', 'stung', 'ABB', 'B1', 'chaqmoq (ari)', 'жалить'),
    ('strike', 'struck', 'struck', 'ABB', 'B1', 'urmoq', 'ударять'),
    ('swear', 'swore', 'sworn', 'ABC', 'B1', 'qasam ichmoq, so''kinmoq', 'клясться, ругаться'),
    ('sweep', 'swept', 'swept', 'ABB', 'B1', 'supurmoq', 'подметать'),
    ('swing', 'swung', 'swung', 'ABB', 'B1', 'tebranmoq', 'качаться'),
    ('tear', 'tore', 'torn', 'ABC', 'B1', 'yirtmoq', 'рвать'),
    ('upset', 'upset', 'upset', 'AAA', 'B1', 'xafa qilmoq', 'расстраивать'),
    ('deal', 'dealt', 'dealt', 'ABB', 'B1', 'shug''ullanmoq', 'иметь дело'),
    ('bear', 'bore', 'borne', 'ABC', 'B2', 'chidamoq', 'выносить, терпеть'),
    ('bind', 'bound', 'bound', 'ABB', 'B2', 'bog''lamoq', 'связывать'),
    ('breed', 'bred', 'bred', 'ABB', 'B2', 'ko''paytirmoq (hayvon)', 'разводить'),
    ('broadcast', 'broadcast', 'broadcast', 'AAA', 'B2', 'efirga uzatmoq', 'транслировать'),
    ('cling', 'clung', 'clung', 'ABB', 'B2', 'yopishib olmoq', 'цепляться'),
    ('creep', 'crept', 'crept', 'ABB', 'B2', 'sudralmoq, sekin yurmoq', 'ползти, красться'),
    ('flee', 'fled', 'fled', 'ABB', 'B2', 'qochmoq', 'бежать, спасаться'),
    ('fling', 'flung', 'flung', 'ABB', 'B2', 'irg''itmoq', 'швырять'),
    ('forbid', 'forbade', 'forbidden', 'ABC', 'B2', 'taqiqlamoq', 'запрещать'),
    ('forecast', 'forecast', 'forecast', 'AAA', 'B2', 'bashorat qilmoq', 'прогнозировать'),
    ('foresee', 'foresaw', 'foreseen', 'ABC', 'B2', 'oldindan ko''rmoq', 'предвидеть'),
    ('grind', 'ground', 'ground', 'ABB', 'B2', 'maydalamoq', 'молоть'),
    ('kneel', 'knelt', 'knelt', 'ABB', 'B2', 'tiz cho''kmoq', 'становиться на колени'),
    ('leap', 'leapt / leaped', 'leapt / leaped', 'ABB', 'B2', 'sakramoq', 'прыгать'),
    ('mislead', 'misled', 'misled', 'ABB', 'B2', 'chalg''itmoq', 'вводить в заблуждение'),
    ('overtake', 'overtook', 'overtaken', 'ABC', 'B2', 'quvib o''tmoq', 'обгонять'),
    ('quit', 'quit', 'quit', 'AAA', 'B2', 'tashlab ketmoq', 'бросать, уходить'),
    ('seek', 'sought', 'sought', 'ABB', 'B2', 'izlamoq', 'искать'),
    ('sew', 'sewed', 'sewn', 'ABC', 'B2', 'tikmoq', 'шить'),
    ('shed', 'shed', 'shed', 'AAA', 'B2', 'to''kmoq (barg, ko''z yosh)', 'сбрасывать, проливать'),
    ('shrink', 'shrank', 'shrunk', 'ABC', 'B2', 'kichraymoq', 'сжиматься'),
    ('slide', 'slid', 'slid', 'ABB', 'B2', 'sirpanmoq', 'скользить'),
    ('sow', 'sowed', 'sown', 'ABC', 'B2', 'ekmoq (urug'')', 'сеять'),
    ('speed', 'sped', 'sped', 'ABB', 'B2', 'tezlashmoq', 'мчаться'),
    ('spin', 'spun', 'spun', 'ABB', 'B2', 'aylanmoq', 'вращаться'),
    ('spit', 'spat', 'spat', 'ABB', 'B2', 'tupurmoq', 'плевать'),
    ('split', 'split', 'split', 'AAA', 'B2', 'bo''lmoq, ajratmoq', 'раскалывать, делить'),
    ('stink', 'stank', 'stunk', 'ABC', 'B2', 'sasimoq', 'вонять'),
    ('strive', 'strove', 'striven', 'ABC', 'B2', 'intilmoq', 'стремиться'),
    ('undertake', 'undertook', 'undertaken', 'ABC', 'B2', 'zimmasiga olmoq', 'предпринимать'),
    ('weep', 'wept', 'wept', 'ABB', 'B2', 'yig''lamoq', 'плакать'),
    ('wind', 'wound', 'wound', 'ABB', 'B2', 'o''ramoq, buramoq', 'наматывать, заводить'),
    ('withdraw', 'withdrew', 'withdrawn', 'ABC', 'B2', 'qaytarib olmoq, chiqib ketmoq', 'снимать, отступать'),
    ('arise', 'arose', 'arisen', 'ABC', 'C1', 'paydo bo''lmoq', 'возникать'),
    ('bid', 'bid', 'bid', 'AAA', 'C1', 'taklif qilmoq (narx)', 'предлагать цену'),
    ('dwell', 'dwelt', 'dwelt', 'ABB', 'C1', 'yashamoq, to''xtalib qolmoq', 'обитать, задерживаться'),
    ('forsake', 'forsook', 'forsaken', 'ABC', 'C1', 'tark etmoq', 'покидать'),
    ('inlay', 'inlaid', 'inlaid', 'ABB', 'C2', 'inkrustatsiya qilmoq', 'инкрустировать'),
    ('overhear', 'overheard', 'overheard', 'ABB', 'C1', 'tasodifan eshitib qolmoq', 'подслушать случайно'),
    ('slay', 'slew', 'slain', 'ABC', 'C2', 'o''ldirmoq (adabiy)', 'убивать (книжн.)'),
    ('sling', 'slung', 'slung', 'ABB', 'C1', 'osib qo''ymoq, otmoq', 'швырять, вешать'),
    ('spring', 'sprang', 'sprung', 'ABC', 'C1', 'sakrab chiqmoq', 'прыгать, возникать'),
    ('stride', 'strode', 'stridden', 'ABC', 'C1', 'katta qadam tashlamoq', 'шагать'),
    ('strew', 'strewed', 'strewn', 'ABC', 'C2', 'sochmoq', 'разбрасывать'),
    ('thrust', 'thrust', 'thrust', 'AAA', 'C1', 'turtmoq, tiqmoq', 'толкать, вонзать'),
    ('tread', 'trod', 'trodden', 'ABC', 'C1', 'bosmoq, qadam qo''ymoq', 'ступать'),
    ('uphold', 'upheld', 'upheld', 'ABB', 'C1', 'qo''llab-quvvatlamoq', 'поддерживать'),
    ('withhold', 'withheld', 'withheld', 'ABB', 'C1', 'ushlab qolmoq', 'удерживать'),
    ('withstand', 'withstood', 'withstood', 'ABB', 'C1', 'bardosh bermoq', 'выдерживать'),
    ('wring', 'wrung', 'wrung', 'ABB', 'C1', 'siqmoq, burab siqmoq', 'выжимать'),
    ('behold', 'beheld', 'beheld', 'ABB', 'C2', 'ko''rmoq (adabiy)', 'узреть'),
    ('smite', 'smote', 'smitten', 'ABC', 'C2', 'urmoq (adabiy)', 'поражать (книжн.)'),
    ('abide', 'abode / abided', 'abode / abided', 'ABB', 'C2', 'rioya qilmoq, chidamoq', 'соблюдать, терпеть');

UPDATE irregular_verbs SET note = v.note FROM (VALUES
    ('read',   'Yozilishi bir xil, lekin o''tgan zamon shakllari /red/ deb o''qiladi.'),
    ('lie',    '"Yotmoq" ma''nosida noto''g''ri fe''l. "Yolg''on gapirmoq" ma''nosida to''g''ri: lie – lied – lied.'),
    ('lay',    '"Qo''ymoq, yotqizmoq". lie (yotmoq) ning o''tgan zamoni ham lay — adashtirmang.'),
    ('hang',   '"Osmoq" (narsani). Odamni osib o''ldirish ma''nosida to''g''ri: hang – hanged – hanged.'),
    ('get',    'Britaniya ingliz tilida got, Amerikada ko''pincha gotten.'),
    ('learn',  'learnt — Britaniya, learned — Amerika va hozirgi umumiy shakl.'),
    ('be',     'was — I/he/she/it bilan, were — you/we/they bilan.'),
    ('wind',   '"O''ramoq" ma''nosida /waɪnd/ – wound /waʊnd/. "Shamol" (wind) bilan adashtirmang.'),
    ('bear',   'borne — "chidamoq"; tug''ilish haqida born ishlatiladi: I was born in 2000.'),
    ('shine',  '"Porlamoq" — shone. "Yaltiratmoq (poyabzalni)" ma''nosida to''g''ri: shined.')
) AS v(base, note)
WHERE irregular_verbs.base = v.base;
