"use client";

import type { LearningPlan } from "@engora/types";

import { EmptyState, ErrorState } from "@/components/common/states";
import { SkillIcon } from "@/components/learning/skill-icon";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

import { skillName } from "../labels";

/** Today's structured plan, as generated by the API (never hardcoded in the client). */
export function PlanItems({
  plan,
  isPending,
  error,
  onRetry,
  retrying,
}: {
  plan: LearningPlan | null | undefined;
  isPending: boolean;
  error?: unknown;
  onRetry?: () => void;
  retrying?: boolean;
}) {
  if (isPending) {
    return (
      <div className="grid gap-2.5">
        {[0, 1, 2].map((i) => (
          <Skeleton key={i} className="h-20 rounded-xl" />
        ))}
      </div>
    );
  }
  if (error) return <ErrorState error={error} onRetry={onRetry} />;
  if (!plan || plan.items.length === 0) {
    return (
      <EmptyState
        title="Your plan is being prepared"
        description="It only takes a moment."
        action={
          onRetry && (
            <Button onClick={onRetry} loading={retrying}>
              Build my plan
            </Button>
          )
        }
      />
    );
  }

  const total = plan.items.reduce((sum, item) => sum + item.minutes, 0);
  return (
    <div className="grid gap-3">
      <ol className="grid gap-2.5">
        {plan.items.map((item) => (
          <li key={item.id} className="flex items-center gap-3 rounded-xl border bg-surface/40 p-4 sm:gap-4">
            <span className="grid size-10 shrink-0 place-items-center rounded-lg bg-primary-subtle text-primary-subtle-foreground">
              <SkillIcon code={item.skill} className="size-5" />
            </span>
            <div className="min-w-0 flex-1">
              <p className="text-label text-fg-muted">
                {item.position}. {skillName(item.skill)}
              </p>
              <p className="text-h4">{item.title}</p>
              {item.description && <p className="text-body-sm text-fg-secondary">{item.description}</p>}
            </div>
            <span className="shrink-0 rounded-md border px-2 py-1 text-label tabular-nums text-fg-secondary">{item.minutes} min</span>
          </li>
        ))}
      </ol>
      <p className="text-right text-caption text-fg-muted">{total} minutes a day</p>
    </div>
  );
}
